# **Numpy**

Numpy stands for Numerical Python and it is a general purpose array-processing package. It provides a high performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.

**What is an array ?**

An array is a data structure that stores values of same datatype. In Python, this is the main difference between array and lists. While Python's lists can contain values corresponding to different data types, array in python can only contain values corresponding to same data type.

**Note: Python inbuilt allow only to create one dimesnional arrays. However, to create multidimensional arrays, we need to import numpy library.**

**Creating Array with inbuilt python array class**

In [10]:
# import array
import array

In [13]:
# creating an one dimensional array
arr = array.array('i', [1,2,3,4])
print(arr)
print(type(arr))

array('i', [1, 2, 3, 4])
<class 'array.array'>


**Creating Array using Numpy library**

In [1]:
# import numpy library
import numpy as np

In [15]:
# creating one dimesional array
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [16]:
# creating two dimensional array
arr = np.array([[1,2], [3,4]])
print(arr)
print(type(arr))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


**Indexing**

In [17]:
# we can retreive single element using indexing
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(arr[0])

[1 2 3]


**Slicing**

In [21]:
# we can retreive multiple elements using slicing
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(arr[:-1])

[[1 2 3]
 [4 5 6]]


In [23]:
print(arr[:,1])

[2 5 8]


## **Ways to create arrays**

### **empty() Function**

It is used to create an uninitialized array.

In [41]:
arr = np.empty((3,3), dtype=int)
print(arr)

[[4592982406224789520 4604539990834921879 4603285371213225954]
 [4600880542649900082 4596095273185907116 4604386277088244178]
 [4601894678236935922 4584092155034598176 4599584881378256590]]


### **arange() Function**

It is similar to range function in python. It generate numbers in a specified range with specified stepsize.

In [26]:
arr = np.arange(1,11,2)
print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


### **linspace() Function**

It is used to create one-dimensional array with evenly space between start and end point.

In [40]:
arr = np.linspace(1, 10, num=5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


### **ones() Function**

It helps us to generate n-dimesional array with all the elements as 1.

In [31]:
arr = np.ones((3,3), dtype=float)
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### **zeros() Function**

It helps to generate n-dimesnional array with all the elements as 0.

In [33]:
arr = np.zeros((3,3), dtype=float)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### **random() Function**

It helps to create n-dimensional array where all the elements are random numbers between 0 and 1.

In [39]:
arr = np.random.random((3,3))
print(arr)

[[0.11543524 0.70663156 0.5673408 ]
 [0.4001756  0.19226989 0.68956591]
 [0.45647143 0.02926455 0.32825195]]


### **randint() Function**

It helps to generate random integers between a low and a high value with specified number of elements.

In [35]:
arr = np.random.randint(10, 20, 5)
print(arr)

[16 18 19 10 18]


### **randn() Function**

It helps to n-dimensional array where the distribution of generated number is uniform or normal.

In [38]:
arr = np.random.randn(3,3)
print(arr)

[[ 0.96885596  0.0089218   0.75373601]
 [-0.83325562  1.04873358 -1.36035613]
 [ 0.17365767 -0.52008577  0.8077905 ]]


## **Attributes of Numpy Array**

### **shape Attribute**

It returns a tuple consisting of array dimension

In [43]:
arr = np.array([[1,2], [2,3]])
print(arr)
print("Shape of the Array :")
print(arr.shape)

[[1 2]
 [2 3]]
Shape of the Array :
(2, 2)


### **ndim Attribute**

It returns the dimension of the array

In [44]:
arr = np.array([[1,2], [3,4]])
print(arr)
print("Dimesnion of the array :")
print(arr.ndim)

[[1 2]
 [3 4]]
Dimesnion of the array :
2


### **size Attribute**

It returns the total number of elements in th array

In [45]:
arr = np.array([[1,2], [3,4]])
print(arr)
print("Total Elements :")
print(arr.size)

[[1 2]
 [3 4]]
Total Elements :
4


### **dtype Attribute**

It returns the datatype of the elements in the array

In [46]:
arr = np.array([[1,2], [3,4]], dtype=float)
print(arr)
print("Datatype of array :")
print(arr.dtype)

[[1. 2.]
 [3. 4.]]
Datatype of array :
float64


### **astype() Function**

It is used to change the data type of the elements of an array

In [50]:
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr.dtype)
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[1 2]
 [3 4]]
int64
[[1. 2.]
 [3. 4.]]
float64


## **Array Manipulation**

### **transpose() Function**

It simply moves the row data to column data and vice versa

In [51]:
arr = np.array([[1,2], [3,4]])
print(arr)

[[1 2]
 [3 4]]


In [54]:
# method 1
print(arr.T)

# method 2
arr = np.transpose(arr)
print(arr)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


### **reshape() Function**

It gives a new shape to an existing array but the number of elements should be same compare to existing one.

In [57]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [62]:
np.reshape(arr, (3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **resize() Function**

It gives a new shape to an existing array without considering the number of elements in the existing array.

In [63]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [64]:
np.resize(arr, (2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### **flatten() Function**

It is used to convert n-dimensional array to one-dimensional array

In [65]:
arr = np.array([[1,2], [3,4]])
print(arr)

[[1 2]
 [3 4]]


In [66]:
arr.flatten()

array([1, 2, 3, 4])

## **Array Manipulation Methods**

### **insert() Method**

It is used to insert items to an existing array

In [67]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [72]:
new_arr = np.insert(arr, 1, [10, 20, 30], axis=0)
print(new_arr)

[[ 1  2  3]
 [10 20 30]
 [ 4  5  6]]


### **append() Method**

It is used to add items to the end of an existing array

In [77]:
arr1 = np.array([[1,2], [3,4]])
print(arr1)

[[1 2]
 [3 4]]


In [78]:
arr2 = np.array([[5,6], [7,8]])
print(arr2)

[[5 6]
 [7 8]]


In [81]:
new_arr = np.append(arr1, arr2, axis=0)
print(new_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [82]:
new_arr = np.append(arr1, arr2, axis=1)
print(new_arr)

[[1 2 5 6]
 [3 4 7 8]]


### **delete() Method**

It is used to delete items from an existing array

In [83]:
arr = np.array([[1,2], [3,4]])
print(arr)

[[1 2]
 [3 4]]


In [87]:
new_arr = np.delete(arr, 0, axis=0)
print(new_arr)

[[3 4]]


### **unique() Method**

It returns the unique items from an existing array

In [88]:
arr = np.array([1,1,1,2,2,2,3,3,4,6,7])
print(arr)

[1 1 1 2 2 2 3 3 4 6 7]


In [90]:
unique_elem = np.unique(arr)
print(unique_elem)

[1 2 3 4 6 7]


In [91]:
freq_count = np.unique(arr, return_counts=True)
print(freq_count)

(array([1, 2, 3, 4, 6, 7]), array([3, 3, 2, 1, 1, 1]))


## **Basic Operations**

### **Addition**

In [92]:
np.arange(1,5) + 5

array([6, 7, 8, 9])

**Adding Two arrays**

In [97]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
new_arr = np.add(arr1, arr2)
print(new_arr)

[[ 6  8]
 [10 12]]


### **Subtraction**

In [93]:
np.arange(1,5) - 2

array([-1,  0,  1,  2])

**Subtracting Two Arrays**

In [98]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
new_arr = np.subtract(arr1, arr2)
print(new_arr)

[[-4 -4]
 [-4 -4]]


### **Multiplication**

In [94]:
np.arange(1,5) * 5

array([ 5, 10, 15, 20])

**Multiplying two arrays**

In [99]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
new_arr = np.multiply(arr1, arr2)
print(new_arr)

[[ 5 12]
 [21 32]]


### **Division**

In [95]:
np.arange(10,21) / 2

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

**Dividing two arrays**

In [100]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
new_arr = np.divide(arr1, arr2)
print(new_arr)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
